name: Build

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:

  build:
    
    strategy:
      matrix:
        configuration: [Debug, Release]
    
    runs-on: windows-latest
    
    env:
      working_dir: src
      launcher_dir: NsisoLauncher
      Configuration: ${{ matrix.configuration }}
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Navigate to Workspace
      run: cd $env:working_dir
      
    - name: Nuget restore
      run: nuget restore NsisoLauncher.sln
      
    - name: Build
      run: msbuild $env:launcher_dir /p:configuration=$env:Configuration
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.Configuration }} Build Result
        path: NsisoLauncher\bin\${{ env.Configuration }}
