name: Build

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:

  build:
    
    strategy:
      matrix:
        configuration: [Debug, Release]
    
    runs-on: windows-latest
    
    env:
      working_dir: src
      launcher_dir: src\NsisoLauncher
      test_dir: src\NsisoLauncherCoreTest
      Configuration: ${{ matrix.configuration }}
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup vstest
      uses: darenm/Setup-VSTest@v1
      
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      
    - name: Nuget restore
      run: nuget restore $env:working_dir
      
    - name: Build
      run: msbuild $env:working_dir /p:Configuration=$env:Configuration
      
    - name: Unit Test
      run: VSTest.Console.exe $env:test_dir\bin\$env:Configuration\NsisoLauncherCoreTest.dll
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.Configuration }} Build Result
        path: ${{ env.launcher_dir }}\bin\${{ env.Configuration }}
