name: Build

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:

  build:
    
    strategy:
      matrix:
        configuration: [Debug, Release]
    
    runs-on: windows-latest
    
    env:
      working_dir: src
      launcher_dir: src\NsisoLauncher
      Configuration: ${{ matrix.configuration }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    - name: Restore
      run: msbuild $env:working_dir -t:restore

    - name: Build
      run: msbuild $env:launcher_dir -p:Configuration=$env:Configuration
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build Result
        path: src\NsisoLauncher\bin\$env:Configuration
