name: Build

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:

  build:
    
    strategy:
      matrix:
        configuration: [Debug, Release]
    
    runs-on: windows-latest
    
    env:
      working_dir: src
      launcher_dir: src\NsisoLauncher
      Configuration: ${{ matrix.configuration }}
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      
    - name: Nuget restore
      run: dotnet restore $env:working_dir
      
    - name: Build
      run: dotnet build $env:launcher_dir --configuration $env:Configuration
      
    - name: Test
      run: dotnet test $env:launcher_dir --configuration $env:Configuration
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.Configuration }} Build Result
        path: ${{ env.launcher_dir }}\bin\${{ env.Configuration }}
